# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-04-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_question_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
